### ISSUE TITLE
bitmask in updateBits()

### ISSUE THREAD

**Issue by stupidsing** [jrmelsha/keccak#3]
in Keccak.updateBits()
it looks like (-1L >>> c) should be (-1L >>> 64 - c)
and (-1L >>> inBits) should be (-1L >>> 64 - inBits) ?

It seems c is the number of bits to copy, therefore we need to mask-off the upper (64 - c) input bits
Thanks

**Comment by jrmelsha** [comment]
Correct - thanks. It is in big-endian so we are wanting to mask off the bottom _c_ input bits.
Example: if _c_ is 8, the mask should be 0xff (0b11111111) because we want a mask of size 8.
Thankfully this is not an issue with the implementation itself, as long as you are not utilizing the updateBits function (which is protected access anyway). It is only used in states where it would not cause the algorithm to produce incorrect results. In this case I can actually just use _-c_ rather than _(64-c)_
